-- MySQL Script generated by MySQL Workbench
-- Sun May 20 13:38:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Articulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Articulo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Articulo` (
  `idArticulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `precioUnitario` DOUBLE NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idArticulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `idVenta` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `idVendedor` INT NULL,
  `fechaVenta` DATE NULL,
  `montoVenta` DOUBLE NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idVenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta_has_Articulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venta_has_Articulo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venta_has_Articulo` (
  `Venta_idVenta` INT NOT NULL,
  `Articulo_idArticulo` INT NOT NULL,
  `cantidadVenta` INT NOT NULL,
  PRIMARY KEY (`Venta_idVenta`, `Articulo_idArticulo`),
  INDEX `fk_Venta_has_Articulo_Articulo1_idx` (`Articulo_idArticulo` ASC),
  INDEX `fk_Venta_has_Articulo_Venta_idx` (`Venta_idVenta` ASC),
  CONSTRAINT `fk_Venta_has_Articulo_Venta`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `mydb`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_has_Articulo_Articulo1`
    FOREIGN KEY (`Articulo_idArticulo`)
    REFERENCES `mydb`.`Articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
