-- MySQL Script generated by MySQL Workbench
-- dom 10 jun 2018 15:26:22 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema controlVentas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `controlVentas` ;

-- -----------------------------------------------------
-- Schema controlVentas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlVentas` DEFAULT CHARACTER SET utf8 ;
USE `controlVentas` ;

-- -----------------------------------------------------
-- Table `controlVentas`.`Articulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlVentas`.`Articulo` ;

CREATE TABLE IF NOT EXISTS `controlVentas`.`Articulo` (
  `idArticulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `precioUnitario` DOUBLE NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idArticulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlVentas`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlVentas`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `controlVentas`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlVentas`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlVentas`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `controlVentas`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correoElectronico` VARCHAR(60) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `codigoPostal` VARCHAR(6) NOT NULL,
  `rfc` VARCHAR(13) NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Cliente_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `controlVentas`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlVentas`.`Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlVentas`.`Venta` ;

CREATE TABLE IF NOT EXISTS `controlVentas`.`Venta` (
  `idVenta` INT NOT NULL,
  `fechaVenta` DATE NULL,
  `montoVenta` DOUBLE NULL,
  `estado` VARCHAR(45) NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Empleado1_idx` (`Empleado_idEmpleado` ASC),
  INDEX `fk_Venta_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Venta_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `controlVentas`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `controlVentas`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlVentas`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlVentas`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `controlVentas`.`Usuario` (
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(256) NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`nombreUsuario`),
  INDEX `fk_Usuario_Empleado_idx` (`Empleado_idEmpleado` ASC),
  CONSTRAINT `fk_Usuario_Empleado`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `controlVentas`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlVentas`.`Venta_has_Articulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlVentas`.`Venta_has_Articulo` ;

CREATE TABLE IF NOT EXISTS `controlVentas`.`Venta_has_Articulo` (
  `cantidad` INT NOT NULL,
  `subtotal` DOUBLE NOT NULL,
  `Articulo_idArticulo` INT NOT NULL,
  `Venta_idVenta` INT NOT NULL,
  INDEX `fk_Venta_has_Articulo_Articulo1_idx` (`Articulo_idArticulo` ASC),
  PRIMARY KEY (`Venta_idVenta`),
  CONSTRAINT `fk_Venta_has_Articulo_Articulo1`
    FOREIGN KEY (`Articulo_idArticulo`)
    REFERENCES `controlVentas`.`Articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_has_Articulo_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `controlVentas`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlVentas`.`Sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlVentas`.`Sesion` ;

CREATE TABLE IF NOT EXISTS `controlVentas`.`Sesion` (
  `nombreUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombreUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DROP USER IF EXISTS 'usuarioVentas'@'localhost';
CREATE USER 'usuarioVentas'@'localhost' IDENTIFIED BY 'usuarioVentas';
GRANT select,insert,delete,update ON controlVentas.Articulo TO 'usuarioVentas'@'localhost';
GRANT select,insert,delete,update ON controlVentas.Cliente TO 'usuarioVentas'@'localhost';
GRANT select,insert,delete,update ON controlVentas.Venta TO 'usuarioVentas'@'localhost';
GRANT select,insert,delete,update ON controlVentas.Venta_has_Articulo TO 'usuarioVentas'@'localhost';
GRANT select,insert,delete,update ON controlVentas.Sesion TO 'usuarioVentas'@'localhost';
GRANT select ON controlVentas.Empleado TO 'usuarioVentas'@'localhost';

DROP USER IF EXISTS 'usuarioUsuarios'@'localhost';
CREATE USER 'usuarioUsuarios'@'localhost' IDENTIFIED BY 'usuarioUsuarios';
GRANT select,insert,delete,update ON controlVentas.Usuario TO 'usuarioUsuarios'@'localhost';
GRANT select,insert,delete,update ON controlVentas.Empleado TO 'usuarioUsuarios'@'localhost';
GRANT select,insert,delete,update ON controlVentas.Sesion TO 'usuarioUsuarios'@'localhost';
FLUSH PRIVILEGES;
